# Description: This file contains the configuration for the sashimi plot
# from the rMATS output file
cell_type: PV
timepoint: 48hrs
l1: Ctrl_48h # label for the control group
l2: DOI_48h  # label for the treatment group
exon_s: 1
intron_s: 5
min_counts: 1
event_type: SE
events_dir: /apps/rmats-turbo/PV_48_DOI_output_novel/

# Find the gene name and rMATS event ID in the rMATS output file# 
gene_name: Gria3
rMATS_event_id: 416


# The path to the rMATS output file
bam_path: /apps/rmats-turbo/

S1_name: bams_PV_48_CTRL.txt
S2_name: bams_PV_48_DOI.txt
group_info: grouping.gf
# example indices
# group1name: 1-5
# group2name: 6-10
path_rmats2sashimiplot: /apps/rmats2sashimiplot/


